defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

env_vars_file_path: .env

log:
  experiment_log_dir: ./logs
  metrics_log_path: ./logs/metrics_log.json

wandb:
  enabled: false
  project: test_project
  job_type: inference
  tags: ["test"]
  save_code: false

deterministic:
  random_seed: 1234
  torch_use_deterministic_algorithms: true
  cudnn_backend_deterministic: true

dataloader:
  batch_size: 128
  num_workers: 4

model_file:
  file_type: state_dict
  file_path: "./checkpoints/best.t7"
