defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

env_vars_file_path: .env

log:
  experiment_log_dir: ./logs
  metrics_log_path: ./logs/metrics_log.json

wandb:
  enabled: true
  project: test_project
  job_type: train
  tags: ["test"]
  save_code: false

deterministic:
  random_seed: 1234
  torch_use_deterministic_algorithms: true
  cudnn_backend_deterministic: true

train_epochs: 10
step_by_epoch: false
validate_every: 200

dataloader:
  batch_size: 128
  num_workers: 4

learning_rate: 1e-04

optimizer:
  weight_decay: 0.001

lr_scheduler:
  step_size: 2500
  gamma: 0.01

model_checkpoint:
  checkpoint_every: 200
  save_dir: ./checkpoints

model_snapshot:
  snapshot_every: 200
  save_dir: ./snapshots

resume_training:
  enabled: false
  model_state_dict_path: ./checkpoints/checkpoint.t7
