defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

deterministic:
  random_seed: 1234
  torch_use_deterministic_algorithms: true
  cudnn_backend_deterministic: true

train_epochs: 10
step_by_epoch: true
checkpoint_every: 1
learning_rate: 0.1

dataloader:
  batch_size: 128
  shuffle: true
  num_workers: 4

optimizer:
  weight_decay: 0.01

lr_scheduler:
  step_size: 10
  gamma: 0.01
