defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

log_filepath:
  experiment: ./logs/log.json
  metrics: ./logs/metrics_log.json

deterministic:
  random_seed: 1234
  torch_use_deterministic_algorithms: true
  cudnn_backend_deterministic: true

train_epochs: 3
step_by_epoch: false
validate_every: 200

dataloader:
  batch_size: 128
  shuffle: true
  num_workers: 4

learning_rate: 1e-04

optimizer:
  weight_decay: 0.001

lr_scheduler:
  step_size: 1000
  gamma: 0.01

model_checkpoint:
  checkpoint_every: 100
  save_dir: ./checkpoints
