defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

epochs: 2
step_by_epoch: true
checkpoint_every: 1
learning_rate: 0.1

dataloader:
  batch_size: 64
  shuffle: true
  num_workers: 2

optimizer:
  weight_decay: 0.1

lr_scheduler:
  step_size: 10
  gamma: 0.01
